apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngsa-java
  namespace: ngsa
  labels:
    app.kubernetes.io/name: ngsa-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngsa-java
  template:
    metadata:
      labels:
        app: ngsa-java
        version: beta-0901-2033
        deploy: 21-09-01-20-33-15
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/ngsa-java:beta
          imagePullPolicy: Always
          env:
          - name: PROMETHEUS
            value: "true"
          - name: ZONE
            value: "az-east"
          - name: REGION
            value: "East"

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi

      nodeSelector:
        agentpool: npuser01

---
apiVersion: v1
kind: Service
metadata:
  name: ngsa-java
  namespace: ngsa
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ngsa-java
